name: Dev

on:
  workflow_dispatch:
  pull_request:
    branches: [ "development" ]

jobs:
  get-xml-values:
    uses: bromba-noesis/workflows-repo/.github/workflows/xml_values.yml@main
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: get-xml-values
    environment: Development
    steps:
      - name: deploy
        run: echo deploying to Dev...

  report_project:
      needs: [get-xml-values, build]
      uses: bromba-noesis/workflows-repo/.github/workflows/wiki_library_self_update.yml@main
      with:
        myEnvironment: Development
        myVersion: ${{needs.get-xml-values.outputs.projVersion}}
      secrets: inherit
