name: Dev

on:
  workflow_dispatch:
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: deploy
        run: echo deploying to Dev...

  report_project:
      needs: build
      uses: bromba-noesis/workflows-repo/.github/workflows/wiki_library_self_update.yml@main
      with:
        myEnvironment: Development
        myVersion: 0.0.2
      secrets: inherit
