name: wiki_library_update_proxy

on: 
    workflow_call:
      inputs:
        myRepo:
          required: true
          type: string
        myEnvironment:
          required: true
          type: string
        myVersion:
          required: true
          type: string
        
jobs:
  update_version:
      uses: bromba-noesis/workflows-repo/.github/workflows/wiki_library_update.yml@main
      with:
        myRepo: ${{ inputs.myRepo }}
        myEnvironment: ${{ inputs.myEnvironment }}
        myVersion: ${{ inputs.myVersion }}
      secrets: inherit
